version: "3"     

services:
    mariadb:
        container_name:             mariadb
        image:                      mariadb:latest
        environment:
            MARIADB_ROOT_PASSWORD:  password
            MARIADB_DATABASE:       curso
            MARIADB_USER:           usuario
            MARIADB_PASSWORD:       password
        ports:
                                  - 172.17.0.1:3306:3306
        volumes:
                                  - /home/ubuntu/environment/datos/mariadb:/var/lib/mysql
